import {test as base,expect,type Page,type Response,type Request,type Route,type ConsoleMessage,type TestInfo} from '@playwright/test';
import type {AssistantMemory,AssistantOverview,AssistantPolicy,AssistantPool} from '../../lib/group-assistant';
import fs from 'node:fs';
type IntegrationSession={baseURL:string;controlURL:string;controlKey:string;ownerToken:string;scopedToken:string;csrf:string};
type ApiJournalEntry={url:string;method:string;request:string|null;status:number;body:unknown};
type IntegrationJournal={api:ApiJournalEntry[];js:string[];console:{text:string;url:string}[];externalIntercepted:string[];failed:{url:string;error:string|undefined}[];assistantResponsesMocked:number};
type DatabaseMemory={id:number;chat_id:number;version:number;content:string;source_operator_id:number|null};
type DatabaseSnapshot={groups:{chat_id:number;config:unknown}[];global_config:unknown;policies:AssistantPolicy[];pools:AssistantPool[];memories:DatabaseMemory[];versions:{memory_id:number;version:number}[];conflicts:{id:number;status:string}[]};
type SeedResult={learned_id:number;accept_id:number;reject_id:number;foreign_id:number};
const session:IntegrationSession=JSON.parse(fs.readFileSync(process.env.CG_BROWSER_IT_SESSION!,'utf8'));
const out=process.env.CG_BROWSER_IT_OUT!;
const path=(chat:number,suffix='')=>`/api/admin/groups/${chat}/assistant${suffix}`;
const test=base.extend<{journal:IntegrationJournal}>({journal:[async({page}:{page:Page},use:(journal:IntegrationJournal)=>Promise<void>,info:TestInfo)=>{
 const j:IntegrationJournal={api:[],js:[],console:[],externalIntercepted:[],failed:[],assistantResponsesMocked:0};const pending:Promise<void>[]=[];
 page.on('pageerror',(e:Error)=>j.js.push(e.message));page.on('console',(m:ConsoleMessage)=>{if(m.type()==='error')j.console.push({text:m.text(),url:m.location().url});});page.on('requestfailed',(r:Request)=>j.failed.push({url:r.url(),error:r.failure()?.errorText}));
 page.on('response',(r:Response)=>{if(new URL(r.url()).pathname.startsWith('/api/'))pending.push((async()=>{let body:unknown;try{body=await r.json();}catch{body=await r.text().catch(()=>'<unavailable>');}j.api.push({url:new URL(r.url()).pathname+new URL(r.url()).search,method:r.request().method(),request:r.request().postData(),status:r.status(),body});})());});
 // ONLY external fonts/SDKs are stubbed. Every local /api request goes over HTTP to real Go+PG.
 await page.route('**/*',(route:Route)=>{if(new URL(route.request().url()).hostname==='127.0.0.1')return route.continue();j.externalIntercepted.push(route.request().url());return route.fulfill({contentType:'application/javascript',body:''});});
 await use(j);await Promise.all(pending);await info.attach('real-api-journal',{body:JSON.stringify(j,null,2),contentType:'application/json'});fs.writeFileSync(`${out}/${info.title.startsWith('desktop')?'desktop':'mobile'}-requests.json`,JSON.stringify(j,null,2));expect.soft(j.js,'whole-cycle uncaught JS errors').toEqual([]);const unexpected=j.console.filter(e=>!/^Failed to load resource: the server responded with a status of (401|403|404|409)/.test(e.text));expect.soft(unexpected,'unexpected console errors').toEqual([]);
 },{auto:true}]});
async function login(page:Page,token=session.ownerToken){await page.context().addCookies([{name:'cg_admin',value:token,url:session.baseURL,httpOnly:true,sameSite:'Lax'},{name:'cg_csrf',value:session.csrf,url:session.baseURL,sameSite:'Lax'}]);}
async function open(page:Page,chat:number){await login(page);await page.goto(`/groups/${chat}/assistant`);await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await expect(page.getByLabel('切换群组')).toBeVisible();}
async function tab(page:Page,name:string){await page.getByRole('button',{name,exact:true}).click();}
async function checkedResponse<T>(response:Promise<Response>,status:number):Promise<T>{const r=await response;const body:T=await r.json();expect(r.status(),`${r.request().method()} ${r.url()} body=${JSON.stringify(body)}`).toBe(status);return body;}
async function write<T=unknown>(page:Page,chat:number,suffix:string,method:string,click:()=>Promise<void>,status=200):Promise<T>{const waiting=page.waitForResponse(r=>new URL(r.url()).pathname===path(chat,suffix)&&r.request().method()===method);await click();return checkedResponse<T>(waiting,status);}
async function snap(page:Page,label:string){const r=await page.request.get(session.controlURL+'/snapshot',{headers:{'X-Browser-Fixture':session.controlKey}});expect(r.status()).toBe(200);const data:DatabaseSnapshot=await r.json();fs.writeFileSync(`${out}/db-${label}.json`,JSON.stringify(data,null,2));return data;}
async function shot(page:Page,name:string,chat:number,loaded:string){await expect(page).toHaveURL(new RegExp(`/groups/${chat}/assistant$`));await expect(page.getByText(loaded,{exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);fs.mkdirSync(`${out}/screenshots`,{recursive:true});await page.screenshot({path:`${out}/screenshots/${name}`,fullPage:true});}
const memoryRow=(page:Page,subject:string)=>page.getByRole('row').filter({has:page.getByText(subject,{exact:true})});

// One complete desktop flow, then independent 390px key path on the other real group.
test('desktop real Next Go PostgreSQL settings pool memory conflict CAS forget and scope',async({page,browser,journal},info)=>{
 const chat=-88001;let before:DatabaseSnapshot,created:AssistantMemory,seed:SeedResult;let savedPolicy:AssistantPolicy;
 await test.step('defaults GET no policy/pool persistence',async()=>{before=await snap(page,'initial');expect(before.policies).toEqual([]);expect(before.pools).toEqual([]);await open(page,chat);await expect(page.getByText('已关闭',{exact:true})).toHaveCount(2);await expect(page.getByText('7 天',{exact:true})).toBeVisible();const after=await snap(page,'after-default-get');expect(after.policies).toEqual([]);expect(after.pools).toEqual([]);await shot(page,'integration-overview.png',chat,'实际状态');});
 await test.step('real settings PUT persists and old guard unchanged',async()=>{await tab(page,'聊天与学习');await page.getByRole('switch',{name:'启用聊天',exact:true}).click();await expect(page.getByRole('switch',{name:'启用普通群聊自动学习'})).not.toBeChecked();await page.getByLabel('聊天模型（必须支持 tools）').selectOption('browser:tools');await page.getByLabel('学习模型',{exact:false}).selectOption('browser:text');await page.getByRole('textbox',{name:/^system prompt/}).fill('Integration initial persisted prompt');await page.getByLabel('追问窗口（秒）').fill('450');const r=await write<{policy:AssistantPolicy}>(page,chat,'','PUT',()=>page.getByRole('button',{name:'按版本保存'}).click());savedPolicy=r.policy;expect(savedPolicy).toMatchObject({version:1,chat_enabled:true,learning_enabled:false,retention_days:7,chat_model_ref:'browser:tools'});await page.reload();await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'聊天与学习');await expect(page.getByRole('textbox',{name:/^system prompt/})).toHaveValue('Integration initial persisted prompt');const db=await snap(page,'after-settings');expect(db.groups).toEqual(before.groups);expect(db.global_config).toEqual(before.global_config);expect(db.policies[0]).toMatchObject({chat_id:chat,version:1,followup_window_sec:450});expect(db.pools).toEqual([]);});
 await test.step('independent registry-backed pool PUT persists without policy writes',async()=>{await tab(page,'模型池');for(const [i,id,ref] of [[0,'ep-main','browser:tools'],[1,'ep-learn','browser:text']] as const){await page.getByRole('button',{name:'从 registry 添加端点'}).click();const row=page.getByRole('table').first().locator('tbody tr').nth(i);await row.locator('input').first().fill(id);await row.locator('select').first().selectOption(ref);await row.locator('select').nth(1).selectOption('primary');}
 await page.getByLabel(/^主端点/).nth(0).selectOption('ep-main');await page.getByLabel(/^主端点/).nth(1).selectOption('ep-learn');await page.getByLabel('最大队列深度').fill('4');await page.getByLabel('最大排队等待（秒）').fill('8');const r=await write<AssistantPool>(page,chat,'/model-pool','PUT',()=>page.getByRole('button',{name:'按版本保存'}).click());expect(r.version).toBe(1);await page.reload();await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'模型池');await expect(page.getByLabel(/^主端点/).first()).toHaveValue('ep-main');await expect(page.getByLabel('最大队列深度')).toHaveValue('4');const db=await snap(page,'after-pool');expect(db.pools[0]).toMatchObject({chat_id:chat,version:1});expect(db.policies[0].version).toBe(1);expect(db.policies[0].system_prompt).toBe(savedPolicy.system_prompt);expect(db.groups).toEqual(before.groups);expect(db.global_config).toEqual(before.global_config);await expect(page.getByText('队列 0',{exact:true})).toBeVisible();await shot(page,'integration-model-pool.png',chat,'primary-overflow 模型池');});
 await test.step('UI creates actual base fact edits then versions and source render',async()=>{await tab(page,'记忆中心');await page.getByRole('button',{name:'新增基础事实'}).click();let d=page.getByRole('dialog');await d.getByLabel('主题',{exact:true}).fill('Integration UI base fact');await d.getByLabel('有效范围').fill('long_term');await d.getByLabel('事实内容').fill('Integration base v1');await d.getByLabel('来源摘要（可选）').fill('Integration administrator note');created=(await write<{memory:AssistantMemory}>(page,chat,'/memories','POST',()=>d.getByRole('button',{name:'保存更正'}).click(),201)).memory;expect(created).toMatchObject({version:1,memory_type:'base',authority_level:'admin_base',source:{operator_id:901}});await expect(d).toHaveCount(0);await memoryRow(page,'Integration UI base fact').getByRole('button',{name:'编辑',exact:true}).click();d=page.getByRole('dialog');await d.getByLabel('事实内容').fill('Integration base v2');const r=await write<{memory:AssistantMemory}>(page,chat,`/memories/${created.id}`,'PUT',()=>d.getByRole('button',{name:'保存更正'}).click());expect(r.memory).toMatchObject({version:2,authority_level:'admin_explicit'});await expect(d).toHaveCount(0);await memoryRow(page,'Integration UI base fact').getByRole('button',{name:'来源',exact:true}).click();d=page.getByRole('dialog');await expect(d.getByText('Integration base v1',{exact:true})).toBeVisible();await expect(d.getByText(/当前版本 v2/)).toBeVisible();await expect(d.getByText(/operator：browser-owner/)).toBeVisible();await page.keyboard.press('Escape');const db=await snap(page,'after-memory-edit');expect(db.memories.find(m=>m.id===created.id)).toMatchObject({content:'Integration base v2',version:2,source_operator_id:901});expect(db.versions.filter(v=>v.memory_id===created.id).map(v=>v.version).sort()).toEqual([1,2]);});
 await test.step('seed actual approved learned source conflicts; UI explicit accept and reject',async()=>{const r=await page.request.post(session.controlURL+'/seed',{headers:{'X-Browser-Fixture':session.controlKey}});expect(r.status()).toBe(200);seed=await r.json();await page.reload();await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'记忆中心');await expect(page.getByText('Integration learned subject',{exact:true})).toBeVisible();page.on('dialog',d=>d.accept());
 // Locate exact conflict card; each card owns its accept/reject buttons.
 const card=(title:string)=>page.getByText(title,{exact:true}).locator('xpath=ancestor::div[contains(@class,"rounded-xl")][1]');
 const start=journal.api.length;await write(page,chat,`/conflicts/${seed.accept_id}/resolve`,'POST',()=>card('Integration accept conflict').getByRole('button',{name:'接受',exact:true}).click());await expect(page.getByText(/^冲突已接受，并已以当前管理员明确纠正/)).toBeVisible();await write(page,chat,`/conflicts/${seed.reject_id}/resolve`,'POST',()=>card('Integration reject conflict').getByRole('button',{name:'拒绝',exact:true}).click());await expect(page.getByText('没有待处理冲突',{exact:true})).toBeVisible();const db=await snap(page,'after-conflicts');expect(db.memories.find(m=>m.id===seed.learned_id)).toMatchObject({content:'Integration accept candidate',authority_level:'admin_explicit',source_type:'admin_conflict_accept',source_operator_id:901,source_operator_name:'browser-owner',source_message_id:700,source_chat_id:chat,version:2});expect(db.conflicts.find(c=>c.id===seed.reject_id)!.status).toBe('rejected');await expect.poll(()=>journal.api.slice(start).some(x=>x.method==='POST'&&x.url.endsWith(`/conflicts/${seed.accept_id}/resolve`))).toBe(true);const entries=journal.api.slice(start),get=entries.findIndex(x=>x.method==='GET'&&x.url===path(chat,`/memories/${seed.learned_id}`)),post=entries.findIndex(x=>x.method==='POST'&&x.url.endsWith(`/conflicts/${seed.accept_id}/resolve`));expect(get).toBeGreaterThanOrEqual(0);expect(get).toBeLessThan(post);expect(JSON.parse(entries[post].request!)).toEqual({accept:true,expected_memory_version:1,resolution_mode:'admin_explicit_correction'});});
 await test.step('second authenticated client commits; stale browser PUT409 retains draft',async()=>{await page.reload();await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'聊天与学习');const input=page.getByRole('textbox',{name:/^system prompt/});await input.fill('Integration unsaved concurrent draft');const other=await browser.newContext({baseURL:session.baseURL});try{await other.addCookies([{name:'cg_admin',value:session.scopedToken,url:session.baseURL},{name:'cg_csrf',value:session.csrf,url:session.baseURL}]);const current:AssistantOverview=await (await other.request.get(path(chat))).json();const {chat_id,version,created_at,updated_at,updated_by,...body}=current.policy;const r=await other.request.put(path(chat),{headers:{'X-CSRF-Token':session.csrf},data:{...body,expected_version:version,system_prompt:'Integration second client committed'}});expect(r.status(),await r.text()).toBe(200);await info.attach('second-client-real-commit',{body:await r.body(),contentType:'application/json'});await write(page,chat,'','PUT',()=>page.getByRole('button',{name:'按版本保存'}).click(),409);await expect(page.getByText(/版本冲突：草稿已保留/).first()).toBeVisible();await expect(input).toHaveValue('Integration unsaved concurrent draft');await expect(page.getByText('群助手配置已保存',{exact:true})).toHaveCount(0);const db=await snap(page,'after-cas409');expect(db.policies[0].system_prompt).toBe('Integration second client committed');await page.getByRole('button',{name:'取消草稿'}).click();}finally{await other.close();}});
 await test.step('forget persists inactive and never claims Telegram deletion',async()=>{await tab(page,'记忆中心');const messages:string[]=[];page.removeAllListeners('dialog');page.on('dialog',async d=>{messages.push(d.message());await d.accept();});const r=await write<{remote_telegram_deleted:boolean}>(page,chat,`/memories/${created.id}/forget`,'POST',()=>memoryRow(page,'Integration UI base fact').getByRole('button',{name:'忘记',exact:true}).click());expect(r.remote_telegram_deleted).toBe(false);expect(messages[0]).toContain('不会删除 Telegram');await expect(memoryRow(page,'Integration UI base fact')).toHaveCount(0);const recalled=await page.request.get(path(chat,'/memories'));expect((await recalled.json() as {memories:AssistantMemory[]}).memories.some(m=>m.id===created.id)).toBe(false);const db=await snap(page,'after-forget');expect(db.memories.find(m=>m.id===created.id)).toMatchObject({active:false,forgotten_by:901});expect(db.versions.filter(v=>v.memory_id===created.id).length).toBeGreaterThanOrEqual(2);});
 await test.step('history literal/current scope; status/tools actual DTO; foreign404 and scopedJWT403',async()=>{await page.getByLabel('关键词',{exact:true}).fill('50%');await page.getByLabel('thread_id',{exact:true}).fill('11');await page.getByLabel('sender_id',{exact:true}).fill('903');await page.getByRole('button',{name:'检索历史',exact:true}).click();await expect(page.getByText('Integration public accepted quote 50%',{exact:true})).toBeVisible();await expect(page.getByText('Integration other group 50%',{exact:true})).toHaveCount(0);await expect(page.getByText('Integration expired 50%',{exact:true})).toHaveCount(0);await shot(page,'integration-memory.png',chat,'Integration learned subject');await tab(page,'只读技能');await expect(page.getByText('write_tools：空 · server_bound_scope：true',{exact:true})).toBeVisible();await expect(page.getByText('只读',{exact:true})).toHaveCount(3);const foreign=await page.request.get(path(chat,`/memories/${seed.foreign_id}/versions`));expect(foreign.status()).toBe(404);await info.attach('real-foreign-404',{body:await foreign.body(),contentType:'application/json'});
 const limited=await browser.newContext({baseURL:session.baseURL});try{const p=await limited.newPage();await login(p,session.scopedToken);const forbidden=await limited.request.get(path(-88002));expect(forbidden.status()).toBe(403);await info.attach('real-scope-403',{body:await forbidden.body(),contentType:'application/json'});}finally{await limited.close();}const final=await snap(page,'desktop-final');expect(final.groups).toEqual(before.groups);expect(final.global_config).toEqual(before.global_config);});
});

test('mobile 390 real settings persistence and memory create edit',async({page},info)=>{
 const chat=-88002;await page.setViewportSize({width:390,height:844});await open(page,chat);await tab(page,'聊天与学习');await page.getByRole('switch',{name:'启用普通群聊自动学习'}).click();await page.getByLabel('学习模型',{exact:false}).selectOption('browser:text');await page.getByRole('textbox',{name:/^system prompt/}).fill('Integration mobile persisted');await write(page,chat,'','PUT',()=>page.getByRole('button',{name:'按版本保存'}).click());await page.reload();await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'聊天与学习');await expect(page.getByRole('textbox',{name:/^system prompt/})).toHaveValue('Integration mobile persisted');await tab(page,'记忆中心');await page.getByRole('button',{name:'新增基础事实'}).click();let d=page.getByRole('dialog');await d.getByLabel('主题',{exact:true}).fill('Integration mobile fact');await d.getByLabel('事实内容').fill('Mobile database v1');await d.getByLabel('有效范围').fill('long_term');const created=(await write<{memory:AssistantMemory}>(page,chat,'/memories','POST',()=>d.getByRole('button',{name:'保存更正'}).click(),201)).memory;await expect(d).toHaveCount(0);await memoryRow(page,'Integration mobile fact').getByRole('button',{name:'编辑',exact:true}).click();d=page.getByRole('dialog');await d.getByLabel('事实内容').fill('Mobile database v2');await write(page,chat,`/memories/${created.id}`,'PUT',()=>d.getByRole('button',{name:'保存更正'}).click());await expect(d).toHaveCount(0);await shot(page,'integration-mobile.png',chat,'Integration mobile fact');const db=await snap(page,'mobile-final');expect(db.memories.find(m=>m.id===created.id)).toMatchObject({chat_id:chat,version:2,content:'Mobile database v2',source_operator_id:901});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await info.attach('mobile-real-persistence',{body:JSON.stringify({chat,created_id:created.id}),contentType:'application/json'});
});
