import {test,expect,openAssistant,tab,memoryTab,configuredPool,deferred,login,groups,memory} from './assistant-fixtures';
import {mini} from './ui-fixtures';

for(const action of ['tab','group','link','back','miniBack'])test(`pool owner dirty ${action} cancel URL content then accept`,async({page,api})=>{
 api.pools[-1001]=configuredPool();if(action==='miniBack')await mini(page);await login(page);await page.goto('/assistant');await page.getByRole('button',{name:new RegExp(groups[0].title)}).click();await expect(page.getByLabel('切换群组')).toBeVisible();await tab(page,'模型池');const input=page.getByLabel('最大队列深度');await input.fill('19');let accept=false;const messages:string[]=[];page.on('dialog',async d=>{messages.push(d.message());accept?await d.accept():await d.dismiss();});
 const act=async()=>{if(action==='tab')await tab(page,'只读技能');else if(action==='group')await page.getByLabel('切换群组').selectOption('-1002');else if(action==='link')await page.getByRole('link',{name:'查看现有群审核策略（只读链接）',exact:true}).click();else if(action==='back')await page.goBack();else await page.evaluate(()=>(window as any).__miniBack());};await act();await page.waitForTimeout(400);await expect(page).toHaveURL(/-1001\/assistant$/);await expect(input).toHaveValue('19');await expect(page.getByLabel('切换群组')).toHaveValue('-1001');expect(messages).toHaveLength(1);accept=true;await act();
 if(action==='tab')await expect(page.getByText('当前策略 allowlist',{exact:true})).toBeVisible();else if(action==='group')await expect(page).toHaveURL(/-1002\/assistant$/);else if(action==='link')await expect(page).toHaveURL(/\/groups\/-1001$/);else await expect(page).toHaveURL(/\/assistant$/);expect(api.writes).toEqual([]);
});
for(const action of ['back','miniBack'])test(`memory modal ${action} cancel URL content then accept`,async({page,api})=>{
 if(action==='miniBack')await mini(page);await login(page);await page.goto('/assistant');await page.getByRole('button',{name:new RegExp(groups[0].title)}).click();await expect(page.getByLabel('切换群组')).toBeVisible();await memoryTab(page);await page.getByRole('button',{name:'新增基础事实'}).click();const input=page.getByRole('dialog').getByLabel('主题',{exact:true});await input.fill('Memory owner navigation draft');let accept=false;const messages:string[]=[];page.on('dialog',async d=>{messages.push(d.message());accept?await d.accept():await d.dismiss();});const act=async()=>action==='back'?page.goBack():page.evaluate(()=>(window as any).__miniBack());await act();await page.waitForTimeout(400);await expect(page).toHaveURL(/-1001\/assistant$/);await expect(input).toHaveValue('Memory owner navigation draft');expect(messages).toHaveLength(1);accept=true;await act();await expect(page).toHaveURL(/\/assistant$/);await expect(page.getByRole('dialog')).toHaveCount(0);expect(api.writes).toEqual([]);
});
test('memory saving second keyboard edit not silently discarded',async({page,api},info)=>{
 await openAssistant(page);await memoryTab(page);await page.getByRole('row').filter({hasText:'Fixture -1001 事实1'}).getByRole('button',{name:'编辑',exact:true}).click();const dialog=page.getByRole('dialog'),input=dialog.getByLabel('事实内容');await input.fill('Fixture first snapshot');const gate=deferred();api.rules.push({match:/\/memories\/1$/,method:'PUT',wait:gate.wait,once:true});try{await dialog.getByRole('button',{name:'保存更正'}).click();await expect.poll(()=>api.writes.length).toBe(1);await expect(input).toBeDisabled();await input.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('Fixture second in flight');const edited=await input.inputValue();await info.attach('memory-inflight-edit',{body:JSON.stringify({edited,saving:await dialog.getByRole('button',{name:'保存中…'}).isVisible(),submitted:api.writes[0].body}),contentType:'application/json'});gate.release();await expect(page.getByText('管理员更正已保存',{exact:true})).toBeVisible();if(edited==='Fixture second in flight'){await expect(dialog).toBeVisible();await expect(input).toHaveValue(edited);}else{await expect(dialog).toHaveCount(0);expect(api.writes[0].body.content).toBe(edited);}}finally{gate.release();}
});
test('memory source detail out of order cannot replace selected object',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/memories\/1$/,method:'GET',wait:gate.wait,body:{memory:memory()},once:true});try{await page.getByRole('row').filter({hasText:'Fixture -1001 事实1'}).getByRole('button',{name:'来源',exact:true}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:'Fixture -1001 事实1',exact:true})).toBeVisible();await page.keyboard.press('Escape');const loadedSecond=page.waitForResponse(r=>r.url().endsWith('/assistant/memories/2')&&r.status()===200);await page.getByRole('row').filter({hasText:'Fixture -1001 事实2'}).getByRole('button',{name:'来源',exact:true}).click();await loadedSecond;await expect(page.getByRole('dialog').getByRole('heading',{name:'Fixture -1001 事实2',exact:true})).toBeVisible();await expect(page.getByRole('dialog').getByText('Fixture 旧版本事实')).toBeVisible();gate.release();await page.waitForTimeout(300);await expect(page.getByRole('dialog').getByRole('heading',{name:'Fixture -1001 事实2',exact:true})).toBeVisible();}finally{gate.release();}
});
test('picker omits disabled groups and policy never auto enables',async({page,api})=>{
 api.rules.push({match:/\/api\/admin\/groups$/,body:{groups:[groups[0],{...groups[1],enabled:false}]}});await login(page);await page.goto('/assistant');await expect(page.getByRole('button',{name:new RegExp(groups[0].title)})).toBeVisible();await expect(page.getByRole('button',{name:new RegExp(groups[1].title)})).toHaveCount(0);expect(api.writes).toEqual([]);
});
test('tools 403 displays unavailable and no mock execute controls',async({page,api})=>{
 api.rules.push({match:/\/tools$/,status:403});await openAssistant(page);await tab(page,'只读技能');await expect(page.getByText('tools API 无数据',{exact:true})).toBeVisible();await expect(page.getByText('Fixture injected 403',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/试运行|发送消息|执行工具/})).toHaveCount(0);
});
test('runtime half open and unknown transition uses polled numbers including 0ms',async({page,api})=>{
 api.status[-1001].endpoints_status=[{id:'ep-main',role:'primary',model_ref:'fixture:tools',model_label:'Fixture real local',provider_ref:'fixture',current_active:0,max_concurrency:3,is_full:false,status:'half_open',cooldown_remaining_sec:0,supports_tools:true,local_limit_label:'local',remote_quota_observed:'unknown'}];api.dispatches[-1001]=[{id:1,chat_id:-1001,request_id:'fixture-request',task_type:'learning',endpoint_id:'ep-main',model_ref:'fixture:tools',reason:'Fixture half-open observation',status:'ok',latency_ms:0,created_at:'2026-09-01T00:00:00Z'}];await openAssistant(page);await page.clock.install();await tab(page,'模型池');await expect(page.getByText('half_open',{exact:true})).toBeVisible();await expect(page.getByText('0 ms',{exact:true})).toBeVisible();api.status[-1001].endpoints_status[0].status='unknown';api.status[-1001].queue_depth=4;await page.clock.fastForward(20010);await expect(page.getByText('队列 4',{exact:true})).toBeVisible();await expect(page.getByText('half_open',{exact:true})).toHaveCount(0);await expect(page.getByText('unknown',{exact:true}).first()).toBeVisible();expect(api.writes).toEqual([]);
});
test('history search out of order must preserve latest sender thread scope',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/history\?q=older/,wait:gate.wait,once:true,body:{chat_id:-1001,history:[{id:90,chat_id:-1001,thread_id:999,sender_id:999,sender_name:'Fixture OLD SENDER',role:'user',text:'Fixture old history result',approved:true,delivered:true,expires_at:'2099-01-01T00:00:00Z',source:{type:'telegram',id:'90'},created_at:'2026-09-01T00:00:00Z'}],retention_days:7,expired_auto_removed:true}});try{await page.getByLabel('关键词',{exact:true}).fill('older');await expect.poll(()=>api.requests.some(r=>r.path.includes('/history?q=older'))).toBe(true);const loadedNewest=page.waitForResponse(r=>r.url().includes('/history?q=newest')&&r.status()===200);await page.getByLabel('关键词',{exact:true}).fill('newest');await loadedNewest;await expect(page.getByText('Fixture -1001 保留期历史',{exact:true})).toBeVisible();await page.waitForTimeout(100);gate.release();await page.waitForTimeout(300);await expect(page.getByText('Fixture old history result',{exact:true})).toHaveCount(0);}finally{gate.release();}
});
