import {test,expect,openAssistant,tab,memoryTab,configuredPool} from './assistant-fixtures';
import {theme,mini} from './ui-fixtures';
import fs from 'node:fs';
const root='/opt/openbear/workspace/artifacts/clawguard-assistant-implementation/frontend-verification/screenshots';

for(const value of ['emerald','ocean','graphite'])test(`visual ${value} all five tabs no page overflow real fixture screenshots`,async({page,api},info)=>{
 api.pools[-1001]=configuredPool();await openAssistant(page);await theme(page,value);const observations:any[]=[];
 for(const [name,loaded] of [['开始使用','实际状态'],['怎么说话','聊天模型'],['群记忆','Fixture -1001 事实1'],['模型与负载（高级）','模型与负载'],['能查什么','当前启用的查询能力']]){
  await tab(page,name);const loadedLocator=name==='怎么说话'?page.getByRole('heading',{name:'聊天模型',exact:true}):page.getByText(loaded,{exact:true});await expect(loadedLocator).toBeVisible();await expect(page).toHaveURL(/\/groups\/-1001\/assistant$/);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('html')).toHaveAttribute('data-theme',value);
  const geometry=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body.scrollWidth,overflow:[...document.querySelectorAll('main *')].filter(el=>{const r=el.getBoundingClientRect();return r.right>innerWidth+1&&getComputedStyle(el).position!=='fixed';}).slice(0,12).map(el=>({tag:el.tagName,class:el.className,right:el.getBoundingClientRect().right})),tables:[...document.querySelectorAll('table')].map(el=>({width:el.clientWidth,parentWidth:el.parentElement!.clientWidth,overflow:getComputedStyle(el.parentElement!).overflowX}))}));observations.push({tab:name,...geometry});expect.soft(geometry.scroll,`${name} document horizontal overflow`).toBe(page.viewportSize()!.width);expect.soft(geometry.body,`${name} body overflow`).toBeLessThanOrEqual(page.viewportSize()!.width);for(const table of geometry.tables)if(table.width>table.parentWidth)expect.soft(table.overflow).toBe('auto');
  let shot='';if(info.project.name==='desktop'&&value==='emerald'&&name==='开始使用')shot='assistant-overview.png';if(info.project.name==='desktop'&&value==='ocean'&&name==='群记忆')shot='assistant-memory.png';if(info.project.name==='desktop'&&value==='graphite'&&name==='模型与负载（高级）')shot='assistant-pool-graphite.png';if(info.project.name==='mobile'&&page.viewportSize()!.width===390&&value==='emerald'&&name==='开始使用')shot='assistant-mobile.png';
  // Route, loaded DTO, theme, and no modal asserted before each real Next screenshot.
  fs.mkdirSync(root,{recursive:true});const file=shot||`assistant-${info.project.name}-${page.viewportSize()!.width}-${value}-${['开始使用','怎么说话','群记忆','模型与负载（高级）','能查什么'].indexOf(name)}.png`;await page.screenshot({path:`${root}/${file}`,fullPage:true});await info.attach(file,{path:`${root}/${file}`,contentType:'image/png'});await info.attach('screenshot-ready',{body:JSON.stringify({file,route:page.url(),loaded,theme:value,fixture:true,online:false,modal:false}),contentType:'application/json'});
 }
 await info.attach('all-tab-geometry',{body:JSON.stringify(observations),contentType:'application/json'});
});
test('three themes retain settings and open memory modal values contrast',async({page},info)=>{
 await openAssistant(page);await tab(page,'模型与负载（高级）');await page.getByText('备用模型、排队与回答随机程度',{exact:true}).click();const input=page.getByLabel('默认系统指令');await input.fill('Fixture theme retained');const colors:any[]=[];
 for(const t of ['emerald','ocean','graphite']){await theme(page,t);await expect(input).toHaveValue('Fixture theme retained');const c=await input.evaluate(el=>{const s=getComputedStyle(el);return {color:s.color,bg:s.backgroundColor,base:getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()};});colors.push({theme:t,...c});const rgb=(s:string)=>s.match(/[\d.]+/g)!.map(Number);const bg=rgb(c.bg),base=[1,3,5].map(i=>parseInt(c.base.slice(i,i+2),16));const composite=bg.slice(0,3).map((n,i)=>n*(bg[3]??1)+base[i]*(1-(bg[3]??1)));const lum=(v:number[])=>v.slice(0,3).map(n=>n/255<=.04045?n/255/12.92:((n/255+.055)/1.055)**2.4).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0);const a=lum(rgb(c.color)),b=lum(composite);expect.soft((Math.max(a,b)+.05)/(Math.min(a,b)+.05),t+' input contrast').toBeGreaterThanOrEqual(4.5);}
 page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'取消草稿'}).click();await memoryTab(page);await page.getByRole('button',{name:'新增基础事实'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('主题',{exact:true}).fill('Fixture modal retained');for(const t of ['emerald','ocean','graphite']){await theme(page,t);await expect(dialog).toBeVisible();await expect(dialog.getByLabel('主题',{exact:true})).toHaveValue('Fixture modal retained');}await info.attach('input-contrast-colors',{body:JSON.stringify(colors),contentType:'application/json'});
});
for(const value of ['emerald','ocean','graphite'])test(`Mini ${value} safe area save hit targets navigation and modal`,async({page,api},info)=>{
 await mini(page);await openAssistant(page);await page.evaluate(()=>document.documentElement.style.setProperty('--tg-safe-area-inset-bottom','34px'));
 if(info.project.name==='mobile'){await page.getByRole('button',{name:'全部',exact:true}).click();await theme(page,value);await page.getByRole('button',{name:'关闭',exact:true}).click();}else await theme(page,value);
 await tab(page,'模型与负载（高级）');await page.getByText('备用模型、排队与回答随机程度',{exact:true}).click();await page.getByLabel('默认系统指令').fill('Fixture Mini retained');const save=page.getByRole('button',{name:'保存设置'});await save.scrollIntoViewIfNeeded();const g=await save.evaluate(el=>{const r=el.getBoundingClientRect(),nav=document.querySelector('.miniapp-bottom-nav')?.getBoundingClientRect(),bar=el.closest('.miniapp-savebar')!.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {width:r.width,height:r.height,top:r.top,bottom:r.bottom,navTop:nav?.top,barBottom:bar.bottom,hit:el===hit||el.contains(hit)}});await info.attach('mini-hit-geometry',{body:JSON.stringify(g),contentType:'application/json'});expect.soft(g.hit).toBe(true);if(info.project.name==='mobile')expect.soft(g.height).toBeGreaterThanOrEqual(36);expect.soft(g.bottom).toBeLessThanOrEqual(page.viewportSize()!.height);if(info.project.name==='mobile')expect.soft(g.navTop!-g.barBottom).toBeGreaterThanOrEqual(0);
 await save.click();await expect.poll(()=>api.writes.length).toBe(1);await expect(page.getByText('群助手设置已保存',{exact:true})).toBeVisible();await memoryTab(page);await page.getByRole('button',{name:'新增基础事实'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('主题',{exact:true}).fill('Mini modal draft');page.on('dialog',d=>d.dismiss());await page.keyboard.press('Escape');await expect(dialog.getByLabel('主题',{exact:true})).toHaveValue('Mini modal draft');page.removeAllListeners('dialog');page.on('dialog',d=>d.accept());await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);
 if(info.project.name==='mobile'){await page.getByRole('button',{name:'全部',exact:true}).click();await expect(page.getByRole('link',{name:'群助手',exact:true}).last()).toBeVisible();await page.getByRole('link',{name:'群助手',exact:true}).last().click();await expect(page).toHaveURL(/\/assistant$/);}
});
