import {test,expect,openAssistant,memoryTab,tab,memory,deferred} from './assistant-fixtures';

const factRow=(page:any,id=1)=>page.getByRole('row').filter({has:page.getByText(`Fixture -1001 事实${id}`,{exact:true})});

test('memory all filters server search expiry unknown and source versions readonly',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await expect(factRow(page,3)).toHaveCount(0);await expect(factRow(page,4)).toHaveCount(0);await expect(factRow(page,5)).toContainText('未知');
 for(const [filter,ids] of [['base',[1,3,4]],['learned',[2]],['pending',[5]],['expired',[3]],['inactive',[4]]] as const){await page.getByLabel('列表筛选').selectOption(filter);await expect(page.getByRole('table').first().locator('tbody tr')).toHaveCount(ids.length);for(const id of ids)await expect(factRow(page,id)).toBeVisible();}
 await page.getByLabel('列表筛选').selectOption('base');await page.getByPlaceholder('搜索主题或内容').fill('事实1');await expect(page.getByRole('table').first().locator('tbody tr')).toHaveCount(1);expect(api.requests.some(r=>r.path.includes('q=%E4%BA%8B%E5%AE%9E1')&&r.path.includes('include_inactive=true')&&r.path.includes('limit=200'))).toBe(true);
 await factRow(page).getByRole('button',{name:'来源',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByText('Fixture 旧版本事实')).toBeVisible();await expect(dialog.getByText(/当前第 2 版/)).toBeVisible();await expect(dialog.getByText('来源（服务端只读）')).toBeVisible();await expect(dialog.locator('input,textarea,select')).toHaveCount(0);await expect(dialog.getByText('来源类型：管理员写的')).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);expect(api.writes).toEqual([]);
});
for(const existing of [false,true])test(`memory ${existing?'edit CAS':'create'} exact safe payload`,async({page,api})=>{
 await openAssistant(page);await memoryTab(page);if(existing)await factRow(page).getByRole('button',{name:'编辑',exact:true}).click();else await page.getByRole('button',{name:'新增基础事实'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('主题',{exact:true}).fill('Fixture saved fact');await dialog.getByLabel('事实内容').fill('Fixture content');await dialog.getByLabel('有效范围').fill('本群');await dialog.getByLabel('到期时间').fill('2098-01-02T12:34');await dialog.getByLabel('来源摘要（可选）').fill('Fixture summary');await dialog.getByRole('button',{name:'保存更正'}).click();await expect(dialog).toHaveCount(0);expect(api.writes).toHaveLength(1);const w=api.writes[0];expect(w.path).toBe(`/api/admin/groups/-1001/assistant/memories${existing?'/1':''}`);expect(w.method).toBe(existing?'PUT':'POST');expect(w.body).toMatchObject({subject:'Fixture saved fact',content:'Fixture content',valid_scope:'current_group',source_snippet:'Fixture summary'});if(existing){expect(w.body.expected_version).toBe(2);expect(w.body).not.toHaveProperty('source_type');}else expect(w.body.source_type).toBe('admin_base');expect(Date.parse(w.body.expires_at)).toBeGreaterThan(Date.now());for(const key of ['authority_level','source_message_id','source_chat_id','source_content_hash','operator_id','memory_type','sender_id'])expect(w.body).not.toHaveProperty(key);await expect(page.getByText('Fixture saved fact',{exact:true})).toBeVisible();
});
for(const code of [409,500])test(`memory ${code} retains draft and cancel`,async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await factRow(page).getByRole('button',{name:'编辑',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('事实内容').fill('Fixture correction draft');api.rules.push({match:/\/memories\/1$/,method:'PUT',status:code,once:true});await dialog.getByRole('button',{name:'保存更正'}).click();await expect(page.getByText(code===409?/记忆版本冲突：草稿保留/:/Fixture injected 500/)).toBeVisible();await expect(dialog.getByLabel('事实内容')).toHaveValue('Fixture correction draft');page.on('dialog',d=>d.dismiss());await dialog.getByRole('button',{name:'取消',exact:true}).click();await expect(dialog).toBeVisible();expect(api.writes[0].body.expected_version).toBe(2);
});
test('memory modal keyboard focus trap Esc dirty cancel accept restores trigger',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const trigger=page.getByRole('button',{name:'新增基础事实'});await trigger.click();const dialog=page.getByRole('dialog');const close=dialog.getByRole('button',{name:'关闭',exact:true});await expect(close).toBeFocused();await dialog.getByLabel('主题',{exact:true}).fill('keyboard draft');await dialog.getByLabel('有效范围').fill('本群');await dialog.getByLabel('事实内容').fill('keyboard content');
 await close.focus();await page.keyboard.press('Shift+Tab');expect.soft(await dialog.evaluate(el=>el.contains(document.activeElement)),'reverse Tab must stay in modal').toBe(true);await dialog.getByRole('button',{name:'保存更正'}).focus();await page.keyboard.press('Tab');expect.soft(await dialog.evaluate(el=>el.contains(document.activeElement)),'Tab must stay in modal').toBe(true);
 const input=dialog.getByLabel('主题',{exact:true});await input.focus();let accept=false;const messages:string[]=[];page.on('dialog',async d=>{messages.push(d.message());accept?await d.accept():await d.dismiss();});await page.keyboard.press('Escape');await expect(dialog).toBeVisible();await expect(input).toHaveValue('keyboard draft');await expect(input).toBeFocused();expect(messages).toHaveLength(1);accept=true;await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect.soft(trigger).toBeFocused();expect(api.writes).toEqual([]);
});
test('memory saving Esc cannot dismiss in-flight transaction',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await factRow(page).getByRole('button',{name:'编辑',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('事实内容').fill('pending save');const gate=deferred();api.rules.push({match:/\/memories\/1$/,method:'PUT',wait:gate.wait,status:500,once:true});let confirmations=0;page.on('dialog',async d=>{confirmations++;await d.accept();});
 try{await dialog.getByRole('button',{name:'保存更正'}).click();await expect.poll(()=>api.writes.length).toBe(1);await expect(dialog.getByLabel('事实内容')).toBeDisabled();await page.keyboard.press('Escape');expect.soft(confirmations,'saving must not permit discard').toBe(0);await expect.soft(dialog).toBeVisible();gate.release();await expect(page.getByText(/Fixture injected 500/)).toBeVisible();await expect.soft(dialog.getByLabel('事实内容')).toHaveValue('pending save');await expect(dialog.getByLabel('事实内容')).toBeEnabled();await dialog.getByLabel('事实内容').fill('retry editable draft');await expect(dialog.getByLabel('事实内容')).toHaveValue('retry editable draft');}finally{gate.release();}
});
for(const accept of [false,true])test(`conflict ${accept?'accept':'reject'} correct object and no client authority`,async({page,api})=>{
 await openAssistant(page);await memoryTab(page);let message='';page.on('dialog',async d=>{message=d.message();await d.accept();});await page.getByRole('button',{name:accept?'接受':'拒绝',exact:true}).first().click();await expect.poll(()=>api.writes.length).toBe(1);expect(api.writes[0]).toMatchObject({path:'/api/admin/groups/-1001/assistant/conflicts/1/resolve',method:'POST',body:accept?{accept:true,expected_memory_version:2,resolution_mode:'admin_explicit_correction'}:{accept:false}});expect(api.writes[0].body).toEqual(accept?{accept:true,expected_memory_version:2,resolution_mode:'admin_explicit_correction'}:{accept:false});if(accept){expect(message).toContain('以当前管理员明确更正');const read=api.requests.findIndex(r=>r.path==='/api/admin/groups/-1001/assistant/memories/1'&&r.method==='GET');const write=api.requests.findIndex(r=>r.path.endsWith('/conflicts/1/resolve'));expect(read).toBeGreaterThanOrEqual(0);expect(read).toBeLessThan(write);}expect(message).toContain('Fixture 冲突1');await expect(page.getByText('Fixture 冲突1',{exact:true})).toHaveCount(0);
});
test('forget cancel and accept names object local scope never Telegram deletion',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);let accept=false;const messages:string[]=[];page.on('dialog',async d=>{messages.push(d.message());accept?await d.accept():await d.dismiss();});await factRow(page).getByRole('button',{name:'忘记'}).click();expect(api.writes).toEqual([]);accept=true;await factRow(page).getByRole('button',{name:'忘记'}).click();await expect(page.getByText('已移出本地召回范围；Telegram 原文未删除',{exact:true})).toBeVisible();await expect(factRow(page)).toHaveCount(0);expect(api.writes[0]).toMatchObject({path:'/api/admin/groups/-1001/assistant/memories/1/forget',method:'POST',body:{}});expect(messages.every(m=>m.includes('Fixture -1001 事实1')&&m.includes('不会删除 Telegram')&&m.includes('本地召回/检索范围'))).toBe(true);
});
test('history retention exact query parameters and scoped result',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await page.getByLabel('关键词',{exact:true}).fill('  查询  ');await page.getByLabel('话题编号',{exact:true}).fill('123');await page.getByLabel('成员编号',{exact:true}).fill('456');await page.getByRole('button',{name:'检索历史',exact:true}).click();await expect(page.getByText('成员 456 · 话题 123',{exact:true})).toBeVisible();await expect(page.getByText(/服务端已自动排除超过保留期的原文。 保留天数：7/)).toBeVisible();const r=api.requests.filter(r=>r.path.includes('/history?')).at(-1);expect(Object.fromEntries(new URL(r.path,'http://fixture').searchParams)).toEqual({q:'查询',thread_id:'123',sender_id:'456',limit:'100'});
});
test('memory loading 500 retry',async({page,api})=>{
 await openAssistant(page);const gate=deferred();const rule={match:/\/memories\?/,wait:gate.wait,status:500};api.rules.push(rule);try{await tab(page,'群记忆');await expect(page.getByText('正在加载记忆…')).toBeVisible();gate.release();await expect(page.getByText('记忆列表没有数据')).toBeVisible();api.rules=api.rules.filter(r=>r!==rule);await page.getByRole('button',{name:'重试',exact:true}).click();await expect(factRow(page)).toBeVisible();}finally{gate.release();}
});
test('memory search out of order must keep newest response',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/memories\?q=older/,wait:gate.wait,body:{memories:[{...memory(80),subject:'Fixture obsolete response'}],retention_notice:'old'},once:true});
 try{await page.getByPlaceholder('搜索主题或内容').fill('older');await expect.poll(()=>api.requests.some(r=>r.path.includes('q=older'))).toBe(true);const loadedNewest=page.waitForResponse(r=>r.url().includes('/memories?q=%E4%BA%8B%E5%AE%9E1')&&r.status()===200);await page.getByPlaceholder('搜索主题或内容').fill('事实1');await loadedNewest;await expect(page.getByRole('table').first().locator('tbody tr')).toHaveCount(1);await expect(factRow(page)).toBeVisible();gate.release();await page.waitForTimeout(300);await expect.soft(page.getByText('Fixture obsolete response',{exact:true})).toHaveCount(0);await expect.soft(factRow(page)).toBeVisible();}finally{gate.release();}
});
test('memory group switch removes previous data and pending requests',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await page.getByLabel('切换群组').selectOption('-1002');await expect(page).toHaveURL(/-1002\/assistant$/);await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'群记忆');await expect(page.getByText('Fixture -1002 事实1',{exact:true})).toBeVisible();await expect(page.getByText('Fixture -1001 事实1',{exact:true})).toHaveCount(0);await expect(page.getByText('Fixture -1002 保留期历史',{exact:true})).toBeVisible();await expect(page.getByText('Fixture -1001 保留期历史',{exact:true})).toHaveCount(0);
});
