// Round3 bounded re-verification: final DTO contract + five previously reported defect families.
import {test,expect,openAssistant,tab,memoryTab,configuredPool,deferred,memory} from './assistant-fixtures';
const row=(page:any,id=1)=>page.getByRole('row').filter({has:page.getByText(`Fixture -1001 事实${id}`,{exact:true})});

for(const scope of ['settings','pool','memory'])test(`R3 DRAFT ${scope} native disabled and 500 restores original editable draft`,async({page,api},info)=>{
 api.pools[-1001]=configuredPool();await openAssistant(page);let input,save;
 if(scope==='memory'){await memoryTab(page);await row(page).getByRole('button',{name:'编辑',exact:true}).click();input=page.getByRole('dialog').getByLabel('事实内容');save=page.getByRole('button',{name:'保存更正'});}else{await tab(page,scope==='pool'?'模型池':'聊天与学习');input=scope==='pool'?page.getByLabel('最大队列深度'):page.getByRole('textbox',{name:/^system prompt/});save=page.getByRole('button',{name:'按版本保存'});}
 const original=scope==='pool'?'17':'Fixture preserved snapshot';await input.fill(original);const gate=deferred();api.rules.push({match:scope==='memory'?/\/memories\/1$/:scope==='pool'?/\/model-pool$/:/\/assistant$/,method:'PUT',wait:gate.wait,status:500,once:true});
 try{await save.click();await expect.poll(()=>api.writes.length).toBe(1);await expect(input).toBeDisabled();expect(await input.evaluate(el=>el.matches(':disabled'))).toBe(true);await input.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(scope==='pool'?'19':'must not replace');await expect(input).toHaveValue(original);const controls=await input.evaluate(el=>[...el.closest('fieldset')!.querySelectorAll('input,select,textarea')].map(x=>({tag:x.tagName,disabled:x.matches(':disabled')})));expect(controls.every(x=>x.disabled)).toBe(true);await info.attach('native-saving-lock',{body:JSON.stringify({scope,controls,submitted:api.writes[0]}),contentType:'application/json'});gate.release();await expect(page.getByText('Fixture injected 500',{exact:true}).first()).toBeVisible();await expect(input).toHaveValue(original);await expect(input).toBeEnabled();await input.fill(scope==='pool'?'20':'editable after failure');await expect(input).toHaveValue(scope==='pool'?'20':'editable after failure');}finally{gate.release();}
});
for(const kind of ['create','edit','source'])test(`R3 FOCUS ${kind} Tab loop Escape restore actual trigger`,async({page})=>{
 await openAssistant(page);await memoryTab(page);const trigger=kind==='create'?page.getByRole('button',{name:'新增基础事实'}):row(page).getByRole('button',{name:kind==='edit'?'编辑':'来源',exact:true});await trigger.click();const dialog=page.getByRole('dialog'),close=dialog.getByRole('button',{name:'关闭',exact:true}).first();await expect(close).toBeFocused();
 if(kind==='create'){await dialog.getByLabel('主题',{exact:true}).fill('Fixture focus');await dialog.getByLabel('有效范围').fill('本群');await dialog.getByLabel('事实内容').fill('Fixture focus body');}
 const last=dialog.getByRole('button',{name:kind==='source'?'管理员更正':'保存更正',exact:true});await close.focus();await page.keyboard.press('Shift+Tab');await expect(last).toBeFocused();await page.keyboard.press('Tab');await expect(close).toBeFocused();
 let accept=false;const messages:string[]=[];page.on('dialog',async d=>{messages.push(d.message());accept?await d.accept():await d.dismiss();});if(kind!=='source'){const input=dialog.getByLabel('事实内容');await input.fill('Esc dirty');await input.focus();await page.keyboard.press('Escape');await expect(input).toHaveValue('Esc dirty');await expect(input).toBeFocused();expect(messages).toHaveLength(1);}accept=true;await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();
});
test('R3 FOCUS source to correction then close returns surviving source trigger',async({page})=>{
 await openAssistant(page);await memoryTab(page);const trigger=row(page).getByRole('button',{name:'来源',exact:true});await trigger.click();await page.getByRole('dialog').getByRole('button',{name:'管理员更正'}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:'更正长期记忆'})).toBeVisible();const d=page.getByRole('dialog'),close=d.getByRole('button',{name:'关闭',exact:true}),save=d.getByRole('button',{name:'保存更正',exact:true});await expect(close).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(save).toBeFocused();await page.keyboard.press('Tab');await expect(close).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(trigger).toBeFocused();
});
test('R3 RACE editor versions close reopen other object ignores old version chain',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/memories\/1\/versions$/,wait:gate.wait,body:{versions:Array.from({length:7},(_,i)=>({id:100+i,memory_id:1,version:i+1,content:'Fixture obsolete version',source_type:'admin_base',created_at:'2026-09-01T00:00:00Z'}))},once:true});
 try{await row(page).getByRole('button',{name:'编辑',exact:true}).click();await expect.poll(()=>api.requests.some(r=>r.path.endsWith('/memories/1/versions'))).toBe(true);await page.keyboard.press('Escape');await row(page,2).getByRole('button',{name:'编辑',exact:true}).click();const d=page.getByRole('dialog');await expect(d.getByText('已有版本链 1 条；提交使用当前 v2 CAS。',{exact:true})).toBeVisible();gate.release();await page.waitForTimeout(300);await expect(d.getByLabel('主题',{exact:true})).toHaveValue('Fixture -1001 事实2');await expect(d.getByText('已有版本链 1 条；提交使用当前 v2 CAS。',{exact:true})).toBeVisible();await expect(d.getByText(/已有版本链 7 条/)).toHaveCount(0);}finally{gate.release();}
});
test('R3 RACE pending memory query across groups cannot repopulate old group',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/-1001\/assistant\/memories\?q=delayed/,wait:gate.wait,body:{memories:[{...memory(80),subject:'Fixture OLD GROUP LEAK'}]},once:true});try{await page.getByPlaceholder('搜索当前群记忆').fill('delayed');await expect.poll(()=>api.requests.some(r=>r.path.includes('q=delayed'))).toBe(true);await page.getByLabel('切换群组').selectOption('-1002');await expect(page).toHaveURL(/-1002\/assistant$/);await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'记忆中心');await expect(page.getByText('Fixture -1002 事实1',{exact:true})).toBeVisible();gate.release();await page.waitForTimeout(300);await expect(page.getByText('Fixture OLD GROUP LEAK')).toHaveCount(0);await expect(page.getByText('Fixture -1002 事实1',{exact:true})).toBeVisible();}finally{gate.release();}
});
test('R3 TOOLS primary backup filter and invalid existing reference stays disabled',async({page,api})=>{
 const p=configuredPool();p.config.task_assignments.chat.primary='ep-text';api.pools[-1001]=p;await openAssistant(page);await tab(page,'模型池');const primary=page.getByLabel(/^主端点/).first();await expect(primary.locator('option[value="ep-text"]')).toHaveJSProperty('disabled',true);await expect(primary.locator('option[value="ep-text"]')).toHaveAttribute('disabled','');await expect(primary.locator('option[value="ep-text"]')).toContainText('当前引用不满足 tools');await primary.selectOption('ep-main');await page.getByLabel('有序备用端点').first().fill('ep-text, ep-backup');await expect(page.getByLabel('有序备用端点').first()).toHaveValue('ep-backup');await expect(page.getByLabel(/^主端点/).nth(1).locator('option[value="ep-text"]')).toHaveCount(1);await page.getByRole('button',{name:'按版本保存'}).click();await expect(page.getByText('模型池已保存',{exact:true})).toBeVisible();expect(api.writes[0].body.task_assignments.chat).toEqual({primary:'ep-main',backups:['ep-backup']});
});
for(const stale of [false,true])test(`R3 API conflict current GET version9 ${stale?'CAS409 no success':'explicit correction exact payload'}`,async({page,api})=>{
 api.memories[-1001][0].version=9;await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/conflicts\/1\/resolve$/,method:'POST',wait:gate.wait,once:true});let message='';page.on('dialog',async d=>{message=d.message();await d.accept();});try{await page.getByRole('button',{name:'接受',exact:true}).first().click();await expect.poll(()=>api.writes.length).toBe(1);expect(message).toContain('以当前管理员明确纠正');expect(message).toContain('Fixture 冲突1');expect(api.writes[0].body).toEqual({accept:true,expected_memory_version:9,resolution_mode:'admin_explicit_correction'});const get=api.requests.findIndex(r=>r.method==='GET'&&r.path.endsWith('/memories/1')),put=api.requests.findIndex(r=>r.path.endsWith('/conflicts/1/resolve'));expect(get).toBeGreaterThanOrEqual(0);expect(get).toBeLessThan(put);if(stale)api.memories[-1001][0].version=10;const listBefore=api.requests.filter(r=>r.path.includes('/conflicts?')).length;gate.release();
 if(stale){await expect(page.getByText(/本次未成功接受/)).toBeVisible();await expect(page.getByText(/^冲突已接受/)).toHaveCount(0);await expect.poll(()=>api.requests.filter(r=>r.path.includes('/conflicts?')).length).toBeGreaterThan(listBefore);expect(api.conflicts[-1001]).toHaveLength(2);expect(api.memories[-1001][0].content).toBe('Fixture 本群事实内容 1');expect(api.memories[-1001][0].version).toBe(10);}else{await expect(page.getByText(/^冲突已接受，并已以当前管理员明确纠正/)).toBeVisible();expect(api.memories[-1001][0]).toMatchObject({version:10,authority_level:'admin_explicit',source:{source_type:'admin_conflict_accept',source_message_id:89,source_chat_id:-1001,operator_id:7}});await row(page).getByRole('button',{name:'来源',exact:true}).click();await expect(page.getByRole('dialog').getByText(/source_type/)).toContainText('admin_conflict_accept');await expect(page.getByRole('dialog').getByText(/source_chat_id/)).toContainText('-1001');}}finally{gate.release();}
});
test('R3 API Telegram source invalid PUT409 retains full editor fields',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await row(page,2).getByRole('button',{name:'编辑',exact:true}).click();const d=page.getByRole('dialog');await expect(d.getByText(/以当前管理员明确纠正/)).toContainText('Fixture -1001 事实2');await d.getByLabel('事实内容').fill('Fixture source invalid correction');await d.getByLabel('有效范围').fill('本群');await d.getByLabel('来源摘要（可选）').fill('Fixture preserved source summary');await d.getByRole('button',{name:'保存更正'}).click();await expect(page.getByText(/记忆版本冲突：草稿保留/)).toBeVisible();await expect(d.getByLabel('事实内容')).toHaveValue('Fixture source invalid correction');await expect(d.getByLabel('有效范围')).toHaveValue('本群');await expect(d.getByLabel('来源摘要（可选）')).toHaveValue('Fixture preserved source summary');await expect(d.getByLabel('事实内容')).toBeEnabled();expect(api.writes[0].body).toMatchObject({expected_version:2,valid_scope:'current_group'});for(const key of ['source_type','source_message_id','source_chat_id','source_content_hash','authority_level','operator_id'])expect(api.writes[0].body).not.toHaveProperty(key);expect(api.memories[-1001][1].version).toBe(2);expect(api.memories[-1001][1].source.source_message_id).toBe(88);
});
for(const alias of [false,true])test(`R3 API source ${alias?'alias':'canonical'} type chat id currently_verified readonly`,async({page,api})=>{
 api.memories[-1001][0].source=alias?{type:'telegram_approved_message',chat_id:-1001,message_id:88,currently_verified:false,snippet:'Fixture original'}:{source_type:'admin_explicit_correction',source_chat_id:-1001,source_message_id:88,currently_verified:true,snippet:'Fixture original'};await openAssistant(page);await memoryTab(page);await expect(row(page)).toContainText(`currently_verified=${String(!alias)}`);await row(page).getByRole('button',{name:'来源',exact:true}).click();const d=page.getByRole('dialog');await expect(d.getByText(/source_type/)).toContainText(alias?'telegram_approved_message':'admin_explicit_correction');await expect(d.getByText(/source_chat_id/)).toContainText('-1001');await expect(d.getByText(/消息 ID/)).toContainText('88');await expect(d.getByText(/currently_verified=/)).toContainText(String(!alias));await expect(d.locator('input,textarea,select')).toHaveCount(0);
});
test('R3 API versions404 is visible no invented version chain',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);api.rules.push({match:/\/memories\/1\/versions$/,status:404});await row(page).getByRole('button',{name:'来源',exact:true}).click();await expect(page.getByText('Fixture injected 404',{exact:true})).toBeVisible();await expect(page.getByRole('dialog').getByText('Fixture 旧版本事实')).toHaveCount(0);await expect(page.getByRole('dialog').getByText('暂无 API 返回版本。')).toBeVisible();expect(api.writes).toEqual([]);
});
test('R3 API unknown valid scope rejects locally no network write',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await page.getByRole('button',{name:'新增基础事实'}).click();const d=page.getByRole('dialog');await d.getByLabel('主题',{exact:true}).fill('Fixture invalid scope');await d.getByLabel('事实内容').fill('Fixture invalid scope body');await d.getByLabel('有效范围').fill('arbitrary unbounded scope');await d.getByRole('button',{name:'保存更正'}).click();await expect(page.getByText(/有效范围必须使用服务端支持的范围/)).toBeVisible();expect(api.writes).toEqual([]);await expect(d.getByLabel('有效范围')).toHaveValue('arbitrary unbounded scope');
});
test('R3 strict mock selfcheck rejects forged source and missing foreign versions (not backend proof)',async({page,api},info)=>{
 api.memories[-1002].push(memory(777,-1002));await openAssistant(page);const outcomes=await page.evaluate(async()=>{const base='/api/admin/groups/-1001/assistant';const body={subject:'Fixture negative contract',content:'test-only',valid_scope:'current_group',source_type:'admin_base',source_message_id:888};const cases=[{url:base+'/memories',method:'POST',body},{url:base+'/memories/1',method:'PUT',body:{...body,expected_version:2}},{url:base+'/memories',method:'POST',body:{...body,source_message_id:undefined,source_type:'pinned_announcement'}},{url:base+'/memories/999/versions',method:'GET'},{url:base+'/memories/777/versions',method:'GET'},{url:base+'/conflicts/1/resolve',method:'POST',body:{accept:true}}];const results=[];for(const c of cases){const r=await fetch(c.url,{method:c.method,headers:{'Content-Type':'application/json'},body:c.body?JSON.stringify(c.body):undefined});results.push({url:c.url,status:r.status,error:(await r.json()).error});}return results;});expect(outcomes.map(o=>o.status)).toEqual([400,400,400,404,404,400]);expect(api.memories[-1001][0].version).toBe(2);await info.attach('strict-mock-selfcheck-not-backend-integration',{body:JSON.stringify(outcomes),contentType:'application/json'});
});
