import {test,expect,openAssistant,tab,memoryTab,deferred,memory} from './assistant-fixtures';
const row=(page:any,id=1)=>page.getByRole('row').filter({has:page.getByText(`Fixture -1001 事实${id}`,{exact:true})});

test('saving a setting disables its native controls and restores the draft after failure',async({page,api})=>{
 await openAssistant(page);await tab(page,'模型与负载（高级）');await page.getByText('备用模型、排队与回答随机程度',{exact:true}).click();const input=page.getByLabel('默认系统指令');const save=page.getByRole('button',{name:'保存设置'});await input.fill('Fixture preserved snapshot');const gate=deferred();api.rules.push({match:/\/assistant$/,method:'PUT',wait:gate.wait,status:500,once:true});try{await save.click();await expect.poll(()=>api.writes.length).toBe(1);await expect(input).toBeDisabled();const controls=await input.evaluate(el=>[...el.closest('fieldset')!.querySelectorAll('input,select,textarea')].map(x=>x.matches(':disabled')));expect(controls.every(Boolean)).toBe(true);gate.release();await expect(page.getByText('Fixture injected 500',{exact:true}).first()).toBeVisible();await expect(input).toHaveValue('Fixture preserved snapshot');await expect(input).toBeEnabled();}finally{gate.release();}
});

for(const kind of ['create','edit','source'])test(`memory ${kind} modal traps focus and restores its trigger`,async({page})=>{
 await openAssistant(page);await memoryTab(page);const trigger=kind==='create'?page.getByRole('button',{name:'新增基础事实'}):row(page).getByRole('button',{name:kind==='edit'?'编辑':'来源',exact:true});await trigger.click();const dialog=page.getByRole('dialog'),close=dialog.getByRole('button',{name:'关闭',exact:true}).first();await expect(close).toBeFocused();if(kind==='create'){await dialog.getByLabel('主题',{exact:true}).fill('Fixture focus');await dialog.getByLabel('有效范围').fill('本群');await dialog.getByLabel('事实内容').fill('Fixture focus body');}const last=dialog.getByRole('button',{name:kind==='source'?'管理员更正':'保存更正',exact:true});await close.focus();await page.keyboard.press('Shift+Tab');await expect(last).toBeFocused();await page.keyboard.press('Tab');await expect(close).toBeFocused();let accept=false;const messages:string[]=[];page.on('dialog',async d=>{messages.push(d.message());accept?d.accept():d.dismiss();});if(kind!=='source'){const input=dialog.getByLabel('事实内容');await input.fill('Esc dirty');await input.focus();await page.keyboard.press('Escape');await expect(input).toHaveValue('Esc dirty');await expect(input).toBeFocused();expect(messages).toHaveLength(1);}accept=true;await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();
});

test('source to correction then close returns the surviving source trigger',async({page})=>{
 await openAssistant(page);await memoryTab(page);const trigger=row(page).getByRole('button',{name:'来源',exact:true});await trigger.click();await page.getByRole('dialog').getByRole('button',{name:'管理员更正'}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:'更正群记忆'})).toBeVisible();const d=page.getByRole('dialog'),close=d.getByRole('button',{name:'关闭',exact:true}),save=d.getByRole('button',{name:'保存更正',exact:true});await expect(close).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(save).toBeFocused();await page.keyboard.press('Tab');await expect(close).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(trigger).toBeFocused();
});

test('editor versions race does not replace a newly selected memory',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/memories\/1\/versions$/,wait:gate.wait,body:{versions:Array.from({length:7},(_,i)=>({id:100+i,memory_id:1,version:i+1,content:'Fixture obsolete version',source_type:'admin_base',created_at:'2026-09-01T00:00:00Z'}))},once:true});try{await row(page).getByRole('button',{name:'编辑',exact:true}).click();await expect.poll(()=>api.requests.some(r=>r.path.endsWith('/memories/1/versions'))).toBe(true);await page.keyboard.press('Escape');await row(page,2).getByRole('button',{name:'编辑',exact:true}).click();const d=page.getByRole('dialog');await expect(d.getByText(/已有 1 条版本记录/)).toBeVisible();gate.release();await page.waitForTimeout(300);await expect(d.getByLabel('主题',{exact:true})).toHaveValue('Fixture -1001 事实2');await expect(d.getByText(/已有 7 条/)).toHaveCount(0);}finally{gate.release();}
});

test('pending memory query across groups cannot repopulate old group',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);const gate=deferred();api.rules.push({match:/\/-1001\/assistant\/memories\?q=delayed/,wait:gate.wait,body:{memories:[{...memory(80),subject:'Fixture OLD GROUP LEAK'}]},once:true});try{await page.getByPlaceholder('搜索主题或内容').fill('delayed');await expect.poll(()=>api.requests.some(r=>r.path.includes('q=delayed'))).toBe(true);await page.getByLabel('切换群组').selectOption('-1002');await expect(page).toHaveURL(/-1002\/assistant$/);await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'群记忆');await expect(page.getByText('Fixture -1002 事实1',{exact:true})).toBeVisible();gate.release();await page.waitForTimeout(300);await expect(page.getByText('Fixture OLD GROUP LEAK')).toHaveCount(0);}finally{gate.release();}
});

test('accepting a conflict fetches current version and sends only the explicit correction payload',async({page,api})=>{
 api.memories[-1001][0].version=9;await openAssistant(page);await memoryTab(page);let message='';page.on('dialog',async d=>{message=d.message();await d.accept();});await page.getByRole('button',{name:'接受',exact:true}).first().click();await expect.poll(()=>api.writes.length).toBe(1);expect(message).toContain('当前管理员明确更正');expect(api.writes[0].body).toEqual({accept:true,expected_memory_version:9,resolution_mode:'admin_explicit_correction'});const get=api.requests.findIndex(r=>r.method==='GET'&&r.path.endsWith('/memories/1')),put=api.requests.findIndex(r=>r.path.endsWith('/conflicts/1/resolve'));expect(get).toBeGreaterThanOrEqual(0);expect(get).toBeLessThan(put);
});

test('unknown memory scope is rejected locally without a write',async({page,api})=>{
 await openAssistant(page);await memoryTab(page);await page.getByRole('button',{name:'新增基础事实'}).click();const d=page.getByRole('dialog');await d.getByLabel('主题',{exact:true}).fill('Fixture invalid scope');await d.getByLabel('事实内容').fill('Fixture invalid scope body');await d.getByLabel('有效范围').fill('arbitrary unbounded scope');await d.getByRole('button',{name:'保存更正'}).click();await expect(page.getByText(/有效范围不受支持/)).toBeVisible();expect(api.writes).toEqual([]);await expect(d.getByLabel('有效范围')).toHaveValue('arbitrary unbounded scope');
});

test('chat model capability blocker distinguishes unspecified and unsupported',async({page,api})=>{
 await openAssistant(page);await tab(page,'怎么说话');const chat=page.getByLabel('聊天模型',{exact:true});await chat.selectOption('fixture:text');await expect(page.getByText(/还没声明能调用技能/).first()).toBeVisible();await page.getByRole('switch',{name:'启用聊天',exact:true}).click();await expect(page.getByText(/还没声明能调用技能/).first()).toBeVisible();await chat.selectOption('fixture:no-tools');await expect(page.getByText(/确定不能作为聊天模型/)).toBeVisible();expect(api.writes).toEqual([]);
});
