import {test,expect,openAssistant,tab,configuredPool,deferred} from './assistant-fixtures';

for(const code of [200,409,500])test(`pool independent exact CAS assignment payload response ${code}`,async({page,api})=>{
 api.pools[-1001]=configuredPool();await openAssistant(page);await tab(page,'模型池');await expect(page.getByLabel('策略',{exact:true})).toHaveValue('primary-overflow');await expect(page.getByLabel('策略',{exact:true})).toHaveAttribute('readonly','');
 const row=page.getByRole('table').first().locator('tbody tr').first();await row.locator('input[type=number]').nth(0).fill('2');await row.locator('input[type=number]').nth(1).fill('5');await row.locator('input[type=number]').nth(2).fill('19000');await row.locator('input[type=number]').nth(3).fill('45');await page.getByLabel('最大队列深度').fill('0');await page.getByLabel('最大排队等待（秒）').fill('0');await page.getByLabel('有序备用端点').nth(0).fill('ep-backup, ep-main');await page.getByLabel(/^主端点/).nth(0).selectOption('ep-backup');await page.getByLabel('有序备用端点').nth(0).fill('ep-main');await page.getByLabel('有序备用端点').nth(1).fill('ep-main, ep-backup');
 if(code!==200)api.rules.push({match:/\/model-pool$/,method:'PUT',status:code,once:true});await page.getByRole('button',{name:'按版本保存'}).click();await expect.poll(()=>api.writes.length).toBe(1);const w=api.writes[0];expect(w.path).toBe('/api/admin/groups/-1001/assistant/model-pool');expect(w.body).toMatchObject({expected_version:3,strategy:'primary-overflow',max_queue_depth:0,max_queue_wait_sec:0,task_assignments:{chat:{primary:'ep-backup',backups:['ep-main']},learning:{primary:'ep-text',backups:['ep-main','ep-backup']}}});expect(w.body.endpoints[0]).toMatchObject({id:'ep-main',model_ref:'fixture:tools',priority:2,max_concurrency:5,timeout_ms:19000,cooldown_duration_sec:45});expect(w.body).not.toHaveProperty('policy');expect(w.body).not.toHaveProperty('ai');expect(JSON.stringify(w.body)).not.toMatch(/base_url|api_key/);
 if(code===200)await expect(page.getByText('模型池已保存',{exact:true})).toBeVisible();else{await expect(page.getByText(code===409?/模型池版本冲突/:/Fixture injected 500/).first()).toBeVisible();await expect(page.getByLabel('最大队列深度')).toHaveValue('0');await expect(row.locator('input[type=number]').nth(2)).toHaveValue('19000');await expect(page.getByRole('button',{name:'按版本保存'})).toBeEnabled();}
 expect(api.policies[-1001].max_queue_depth).toBe(10);expect(api.writes).toHaveLength(1);
});
test('pool registry add remove assignment and chat Tools choice filter',async({page,api})=>{
 api.pools[-1001]=configuredPool();await openAssistant(page);await tab(page,'模型池');const chat=page.getByLabel(/^主端点/).nth(0),learning=page.getByLabel(/^主端点/).nth(1);await expect(learning.locator('option[value="ep-text"]')).toHaveCount(1);await expect.soft(chat.locator('option[value="ep-text"]'),'pure text must not be offered to chat').toHaveCount(0);
 await page.getByRole('button',{name:'从 registry 添加端点'}).click();const rows=page.getByRole('table').first().locator('tbody tr');await expect(rows).toHaveCount(4);await expect(rows.last().locator('select').first()).toHaveValue('fixture:tools');await expect(rows.last().locator('option[value="fixture:disabled"]')).toHaveCount(0);await rows.last().getByRole('button',{name:'删除'}).click();await expect(rows).toHaveCount(3);await rows.first().getByRole('button',{name:'删除'}).click();await expect(chat).toHaveValue('');expect(api.writes).toEqual([]);
});
test('pool saving keyboard second edit never lost and cancel draft',async({page,api})=>{
 api.pools[-1001]=configuredPool();await openAssistant(page);await tab(page,'模型池');const input=page.getByLabel('最大队列深度');await input.fill('11');const gate=deferred();api.rules.push({match:/\/model-pool$/,method:'PUT',wait:gate.wait,once:true});try{await page.getByRole('button',{name:'按版本保存'}).click();await expect.poll(()=>api.writes.length).toBe(1);await expect(input).toBeDisabled();await input.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('12');const value=await input.inputValue();gate.release();await expect(page.getByText('模型池已保存',{exact:true})).toBeVisible();await expect.soft(input).toHaveValue(value);await input.fill('13');page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'取消草稿'}).click();await expect(input).toHaveValue('11');}finally{gate.release();}
});
test('registry 403 uses honest hint preserves refs and no privileged alternatives',async({page,api})=>{
 api.policies[-1001].chat_model_ref='fixture:tools';api.pools[-1001]=configuredPool();api.rules.push({match:/\/llm\/models$/,status:403});await openAssistant(page);await tab(page,'聊天与学习');await expect(page.getByText(/当前管理员没有模型 registry 查看能力/).first()).toBeVisible();await expect(page.getByLabel('聊天模型（必须支持 tools）')).toHaveValue('fixture:tools');await tab(page,'模型池');await expect(page.getByRole('button',{name:'从 registry 添加端点'})).toBeDisabled();await expect(page.locator('input[type=password]')).toHaveCount(0);expect(api.requests.filter(r=>r.path.includes('/llm/')).every(r=>r.path==='/api/admin/llm/models')).toBe(true);expect(api.writes).toEqual([]);
});
for(const state of ['empty','observed','403'])test(`runtime ${state} real 0 unknown cooldown dispatch no fake quota`,async({page,api})=>{
 if(state==='403'){api.rules.push({match:/\/status$/,status:403},{match:/\/dispatches\?/,status:403});}
 if(state==='observed'){api.status[-1001].endpoints_status=[{id:'ep-main',model_ref:'fixture:tools',model_label:'Fixture observed',role:'primary',provider_ref:'fixture',current_active:3,max_concurrency:3,is_full:true,status:'cooldown',cooldown_remaining_sec:12,last_error:'Fixture 429 trimmed',supports_tools:true,remote_quota_observed:'unknown',local_limit_label:'local'}];api.status[-1001].queue_depth=2;api.dispatches[-1001]=[{id:1,chat_id:-1001,request_id:'fixture-request',task_type:'chat',endpoint_id:'ep-main',model_ref:'fixture:tools',reason:'Fixture primary full -> ordered backup',status:'failed',error:'Fixture timeout trimmed',latency_ms:null,created_at:'2026-09-01T00:00:00Z'}];}
 await openAssistant(page);await tab(page,'模型池');if(state==='403'){await expect(page.getByText('运行状态无数据',{exact:true})).toBeVisible();await expect(page.getByText('调度记录无数据',{exact:true})).toBeVisible();}else if(state==='empty'){await expect(page.getByText('队列 0',{exact:true})).toBeVisible();await expect(page.getByText('远程配额：unknown',{exact:true})).toBeVisible();await expect(page.getByText('没有 API 返回调度记录')).toBeVisible();await expect(page.getByText('模型池没有 API 返回的端点')).toBeVisible();}else{await expect(page.getByText('Fixture primary full -> ordered backup',{exact:true})).toBeVisible();await expect(page.getByText('cooldown',{exact:true})).toBeVisible();await expect(page.getByText('3 / 3',{exact:false}).first()).toBeVisible();await expect(page.getByText('12s',{exact:true})).toBeVisible();await expect(page.getByText('队列 2',{exact:true})).toBeVisible();}
 expect(api.writes).toEqual([]);await expect(page.locator('input[type=password]')).toHaveCount(0);
});
test('runtime visible polling hidden suspension abort on tab unmount',async({page,api})=>{
 await page.addInitScript(()=>{const original=window.fetch;(window as any).__aborts=[];window.fetch=(input,init)=>{init?.signal?.addEventListener('abort',()=>{(window as any).__aborts.push(String(input));});return original(input,init);};});await openAssistant(page);await page.clock.install();await tab(page,'模型池');const count=()=>api.requests.filter(r=>r.path.endsWith('/status')).length;const initial=count();await page.clock.fastForward(20010);await expect.poll(count).toBe(initial+1);
 await page.evaluate(()=>Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'hidden'}));await page.clock.fastForward(40010);expect(count()).toBe(initial+1);await page.evaluate(()=>Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'visible'}));
 const gate=deferred();api.rules.push({match:/\/status$/,wait:gate.wait,once:true},{match:/\/dispatches\?/,wait:gate.wait,once:true});try{await page.clock.fastForward(20010);await expect.poll(count).toBe(initial+2);await tab(page,'只读技能');await expect.poll(()=>page.evaluate(()=>[...new Set((window as any).__aborts)].sort())).toEqual(['/api/admin/groups/-1001/assistant/dispatches?limit=50','/api/admin/groups/-1001/assistant/status']);const stopped=count();await page.clock.fastForward(60010);expect(count()).toBe(stopped);}finally{gate.release();}
});
test('runtime refresh response from old group must not overwrite new scope',async({page,api})=>{
 await openAssistant(page);await tab(page,'模型池');const gate=deferred();api.rules.push({match:/\/-1001\/assistant\/status$/,wait:gate.wait,body:{...api.status[-1001],queue_depth:99,remote_quota_note:'Fixture OLD GROUP runtime'},once:true});
 try{await page.getByRole('button',{name:'立即刷新'}).click();await expect.poll(()=>api.requests.filter(r=>r.path==='/api/admin/groups/-1001/assistant/status').length).toBe(2);await page.getByLabel('切换群组').selectOption('-1002');await expect(page).toHaveURL(/-1002\/assistant$/);await expect(page.getByText('实际状态',{exact:true})).toBeVisible();await tab(page,'模型池');await expect(page.getByText('队列 0',{exact:true})).toBeVisible();gate.release();await page.waitForTimeout(300);await expect.soft(page.getByText(/Fixture OLD GROUP runtime/)).toHaveCount(0);await expect.soft(page.getByText('队列 0',{exact:true})).toBeVisible();}finally{gate.release();}
});
test('skills only config three read tools server bound scope no pretend run',async({page,api})=>{
 await openAssistant(page);await tab(page,'只读技能');await expect(page.getByText('只读',{exact:true})).toHaveCount(3);await expect(page.getByText('write_tools：空 · server_bound_scope：true',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/试运行|试跑|发送消息|执行工具/})).toHaveCount(0);await page.getByRole('button',{name:'编辑 assistant settings'}).click();await expect(page.getByLabel('网页域名白名单')).toBeVisible();expect(api.writes).toEqual([]);
});
