import {test,expect,login,openAssistant,tab,groups,deferred} from './assistant-fixtures';
import {mini} from './ui-fixtures';

test('entry navigation group choice deep link default disabled and 7d truth',async({page,api})=>{
 await login(page);await page.goto('/groups/-1001');await page.getByRole('link',{name:'打开群助手',exact:true}).click();await expect(page).toHaveURL(/\/groups\/-1001\/assistant$/);await expect(page.getByText('实际状态',{exact:true})).toBeVisible();
 await expect(page.getByText('已关闭',{exact:true})).toHaveCount(2);await expect(page.getByText('7 天',{exact:true})).toBeVisible();await expect(page.getByText(/历史默认政策：7 days/)).toBeVisible();await expect(page.getByText(/不删除 Telegram 远端原文/)).toBeVisible();expect(api.writes).toEqual([]);
 await page.getByRole('link',{name:'群助手',exact:true}).filter({visible:true}).first().click();await expect(page).toHaveURL(/\/assistant$/);await page.getByRole('button',{name:new RegExp(groups[1].title)}).click();await expect(page).toHaveURL(/-1002\/assistant$/);await expect(page.getByText(groups[1].title,{exact:true})).toBeVisible();
});
for(const code of [401,403,404,500])test(`deep link HTTP ${code} and retry`,async({page,api})=>{
 await login(page);api.rules.push({match:/\/groups\/-1001\/assistant$/,status:code,once:true});await page.goto('/groups/-1001/assistant');
 if(code===401){await expect(page).toHaveURL(/\/$/);await expect(page.locator('h1')).toHaveText('ClawGuard');return;}
 await expect(page.getByText(code===403?'没有该群的管理范围':code===404?'群组不存在或已停用':'群助手加载失败',{exact:true})).toBeVisible();await page.getByRole('button',{name:'重试',exact:true}).click();await expect(page.getByText('实际状态',{exact:true})).toBeVisible();
 // Retry should restore optional registry/runtime/group selection too, not just policy.
 await expect.soft(page.getByLabel('切换群组')).toBeVisible();
});
for(const state of ['loading','empty','403'])test(`group picker ${state}`,async({page,api})=>{
 await login(page);const gate=deferred();if(state==='loading')api.rules.push({match:/\/api\/admin\/groups$/,wait:gate.wait,once:true});else api.rules.push({match:/\/api\/admin\/groups$/,status:state==='403'?403:200,body:state==='empty'?{groups:[]}:undefined});
 try{await page.goto('/assistant');if(state==='loading'){await expect(page.getByText('正在加载可管理群组…')).toBeVisible();gate.release();await expect(page.getByRole('button',{name:new RegExp(groups[0].title)})).toBeVisible();}else await expect(page.getByText(state==='empty'?'没有可管理群组':'没有群管理权限',{exact:true})).toBeVisible();}finally{gate.release();}
});
test('settings exact values payload independent enabling and readonly allowlist',async({page,api})=>{
 await openAssistant(page);await tab(page,'聊天与学习');await expect(page.getByRole('switch',{name:'启用聊天',exact:true})).not.toBeChecked();await expect(page.getByRole('switch',{name:'启用普通群聊自动学习'})).not.toBeChecked();
 const chat=page.getByLabel('聊天模型（必须支持 tools）'),learn=page.getByLabel('学习模型',{exact:false});await expect(chat.locator('option[value="fixture:text"]')).toHaveCount(0);await expect(chat.locator('option[value="fixture:disabled"]')).toHaveCount(0);await chat.selectOption('fixture:tools');await learn.selectOption('fixture:text');
 await page.getByRole('switch',{name:'启用聊天',exact:true}).click();await expect(page.getByRole('switch',{name:'启用普通群聊自动学习'})).not.toBeChecked();await page.getByLabel('触发模式').selectOption('mention_only');
 for(const [label,value] of [['追问窗口（秒）','600'],['最多追问轮次','9'],['历史上下文条数','44'],['temperature','0'],['原文保留天数','9'],['最大本地队列深度','0'],['最大排队等待（秒）','22']])await page.getByLabel(label,{exact:false}).fill(value);
 await page.getByRole('textbox',{name:/^system prompt/}).fill('Fixture system only');await page.getByLabel('网页域名白名单').fill('docs.example.test');await page.getByRole('checkbox',{name:'白名单网页读取'}).uncheck();await page.getByRole('button',{name:'按版本保存'}).click();await expect(page.getByText('群助手配置已保存',{exact:true})).toBeVisible();
 expect(api.writes).toHaveLength(1);expect(api.writes[0]).toMatchObject({path:'/api/admin/groups/-1001/assistant',method:'PUT',csrf:'fixture-csrf',body:{expected_version:0,chat_enabled:true,learning_enabled:false,trigger_mode:'mention_only',followup_window_sec:600,max_followup_turns:9,history_limit:44,temperature:0,retention_days:9,chat_model_ref:'fixture:tools',learning_model_ref:'fixture:text',max_queue_depth:0,max_queue_wait_sec:22,system_prompt:'Fixture system only',allow_domains:['docs.example.test'],tool_allowlist:['knowledge_query','conversation_recall']}});
 await page.getByRole('switch',{name:'启用普通群聊自动学习'}).click();await page.getByRole('button',{name:'按版本保存'}).click();await expect.poll(()=>api.writes.length).toBe(2);expect(api.writes[1].body).toMatchObject({expected_version:1,chat_enabled:true,learning_enabled:true});expect(api.writes.some(w=>w.path.endsWith('/config')||w.path.includes('/global-config'))).toBe(false);
});
for(const code of [409,500])test(`settings ${code} retains CAS draft retry and discard`,async({page,api})=>{
 await openAssistant(page);await tab(page,'聊天与学习');const input=page.getByRole('textbox',{name:/^system prompt/});await input.fill('CAS retained');api.rules.push({match:/\/assistant$/,method:'PUT',status:code,once:true});await page.getByRole('button',{name:'按版本保存'}).click();await expect(page.getByText(code===409?/版本冲突：草稿已保留/:/Fixture injected 500/).first()).toBeVisible();await expect(input).toHaveValue('CAS retained');await expect(page.getByRole('button',{name:'按版本保存'})).toBeEnabled();expect(api.writes[0].body.expected_version).toBe(0);
 let accept=false;page.on('dialog',async d=>accept?d.accept():d.dismiss());await page.getByRole('button',{name:'取消草稿'}).click();await expect(input).toHaveValue('CAS retained');accept=true;await page.getByRole('button',{name:'取消草稿'}).click();await expect(input).toHaveValue('');expect(api.writes).toHaveLength(1);
});
test('settings saving keyboard second edit never lost',async({page,api})=>{
 await openAssistant(page);await tab(page,'聊天与学习');const input=page.getByRole('textbox',{name:/^system prompt/});await input.fill('snapshot one');const gate=deferred();api.rules.push({match:/\/assistant$/,method:'PUT',wait:gate.wait,once:true});
 try{await page.getByRole('button',{name:'按版本保存'}).click();await expect.poll(()=>api.writes.length).toBe(1);await expect(input).toBeDisabled();await input.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('snapshot two');const edited=await input.inputValue();await expect(page.getByRole('button',{name:'保存中…'})).toBeDisabled();gate.release();await expect(page.getByText('群助手配置已保存',{exact:true})).toBeVisible();await expect(input).toHaveValue(edited);if(edited==='snapshot two'){await expect(page.getByRole('button',{name:'按版本保存'})).toBeEnabled();await page.getByRole('button',{name:'按版本保存'}).click();await expect.poll(()=>api.writes.length).toBe(2);expect(api.writes[1].body.system_prompt).toBe('snapshot two');}}finally{gate.release();}
});
for(const action of ['tab','group','link','back','miniBack'])test(`dirty navigation ${action} cancel URL content then accept`,async({page,api})=>{
 if(action==='miniBack')await mini(page);await login(page);await page.goto('/assistant');await page.getByRole('button',{name:new RegExp(groups[0].title)}).click();await expect(page.getByLabel('切换群组')).toBeVisible();await tab(page,'聊天与学习');const input=page.getByRole('textbox',{name:/^system prompt/});await input.fill('retained navigation draft');let accept=false;const messages:string[]=[];page.on('dialog',async d=>{messages.push(d.message());accept?await d.accept():await d.dismiss();});
 const act=async()=>{if(action==='tab')await tab(page,'记忆中心');else if(action==='group')await page.getByLabel('切换群组').selectOption('-1002');else if(action==='link')await page.getByRole('link',{name:'群助手',exact:true}).filter({visible:true}).first().click();else if(action==='back')await page.goBack();else await page.evaluate(()=>(window as any).__miniBack());};
 await act();await page.waitForTimeout(400);await expect(page).toHaveURL(/-1001\/assistant$/);await expect(input).toHaveValue('retained navigation draft');await expect(page.getByLabel('切换群组')).toHaveValue('-1001');expect(messages).toHaveLength(1);accept=true;await act();
 if(action==='tab')await expect(page.getByRole('button',{name:'新增基础事实'})).toBeVisible();else if(action==='group'){await expect(page).toHaveURL(/-1002\/assistant$/);await expect(page.getByText(groups[1].title,{exact:true})).toBeVisible();}else{await expect(page).toHaveURL(/\/assistant$/);await expect(page.getByRole('button',{name:new RegExp(groups[0].title)})).toBeVisible();}expect(api.writes).toEqual([]);
});
