import {test,expect,login,openGroup,draftGroup,field,theme,dialogs,mini,group} from './ui-fixtures';
import type {Page} from '@playwright/test';
const artifacts='/opt/openbear/workspace/artifacts/clawguard-ui-implementation';
async function groupFromList(page:Page){await login(page);await page.goto('/groups');await page.getByRole('link',{name:group.title,exact:true}).click();await expect(page).toHaveURL(/groups\/-1001$/);}
async function nav(page:Page,name:string){const link=page.getByRole('link',{name,exact:true}).filter({visible:true});if(await link.count()===0)await page.getByRole('button',{name:'打开菜单'}).click();await page.getByRole('link',{name,exact:true}).filter({visible:true}).first().click();}
for(const value of ['emerald','ocean','graphite'])test(`theme ${value} persists reload and draft`,async({page})=>{await openGroup(page);const input=await draftGroup(page);await theme(page,value);await expect(input).toHaveValue('321');await expect(page.getByRole('combobox',{name:'界面主题'}).filter({visible:true}).first()).toHaveValue(value);expect(await page.evaluate(()=>localStorage.getItem('clawguard-ui-theme'))).toBe(value);dialogs(page,true);await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme',value);await expect(page.getByRole('combobox',{name:'界面主题'}).filter({visible:true}).first()).toHaveValue(value);});
for(const fallback of ['invalid','blocked'])test(`theme fallback ${fallback}`,async({page})=>{await page.addInitScript(mode=>{if(mode==='invalid')localStorage.setItem('clawguard-ui-theme','illegal');else {const original=Storage.prototype.getItem;Storage.prototype.getItem=function(key){if(this===localStorage)throw new Error('fixture storage blocked');return original.call(this,key)};}},fallback);await openGroup(page);await expect(page.locator('html')).toHaveAttribute('data-theme','emerald');await expect(page.getByRole('combobox',{name:'界面主题'}).filter({visible:true}).first()).toHaveValue('emerald');});
for(const status of [200,409,500])test(`group payload false zero empty and response ${status}`,async({page,mock})=>{
 await openGroup(page);const input=await draftGroup(page);await input.fill('0');
 const core=field(page,'入群验证');await core.getByRole('checkbox').first().uncheck();await core.getByRole('switch').first().click();
 const welcome=field(page,'欢迎语');await welcome.getByRole('button',{name:/展开详细/}).click();const rules=field(page,'群规链接');await rules.getByRole('checkbox').uncheck();await rules.locator('input:not([type=checkbox])').fill('');
 mock.status=status;await page.getByRole('button',{name:'保存策略',exact:true}).click();await expect.poll(()=>mock.writes.length).toBe(1);
 expect(mock.writes[0]).toEqual({path:'/api/admin/groups/-1001/config',method:'PUT',body:{fixture_unknown:{preserve:'yes'},verify:{timeout_seconds:0,enabled:false,welcome_message:{rules_link:''}}}});
 if(status===200)await expect(page.getByRole('button',{name:'已保存',exact:true})).toBeDisabled();else {await expect(page.getByText(`Fixture ${status} rejected`,{exact:true})).toBeVisible();await expect(input).toHaveValue('0');await expect(rules.locator('input:not([type=checkbox])')).toHaveValue('');await expect(core.getByRole('switch').first()).toHaveAttribute('aria-checked','false');await expect(page.getByRole('button',{name:'保存策略',exact:true})).toBeEnabled();}
});
test('group restore inheritance and discard',async({page,mock})=>{await openGroup(page);const input=await draftGroup(page);const card=field(page,'超时时长 (秒)');await card.getByRole('checkbox').check();await expect(input).toHaveValue('120');await expect(input).toBeDisabled();await card.getByRole('checkbox').uncheck();await input.fill('222');dialogs(page,true);await page.getByRole('button',{name:'放弃',exact:true}).click();await expect(input).toHaveValue('120');await expect(card.getByRole('checkbox')).toBeChecked();expect(mock.writes).toEqual([]);});
for(const status of [200,409,500])test(`global payload and response ${status}`,async({page,mock})=>{await login(page);await page.goto('/groups/global-config');const number=field(page,'超时时长 (秒)').locator('input');await expect(number).toHaveValue('120');await number.fill('0');await field(page,'启用验证').getByRole('switch').click();await field(page,'群规链接').locator('input').fill('');mock.status=status;await page.getByRole('button',{name:'保存全局策略',exact:true}).click();await expect.poll(()=>mock.writes.length).toBe(1);const body=mock.writes[0].body;expect(body.section).toBe('document');expect(body.version).toBe(7);expect(body.config.verify.timeout_seconds).toBe(0);expect(body.config.verify.enabled).toBe(false);expect(body.config.verify.welcome_message.rules_link).toBe('');expect(body.config.fixture_unknown).toEqual({preserve:'yes'});if(status===200)await expect(page.getByRole('button',{name:'已保存',exact:true})).toBeDisabled();else {await expect(page.getByText(status===409?/配置已被其他人更新/:/Fixture 500 rejected/)).toBeVisible();await expect(number).toHaveValue('0');await expect(page.getByRole('button',{name:'保存全局策略',exact:true})).toBeEnabled();}});
test('global discard and theme preserves draft',async({page})=>{await login(page);await page.goto('/groups/global-config');const input=field(page,'超时时长 (秒)').locator('input');await expect(input).toHaveValue('120');await input.fill('333');await theme(page,'graphite');await expect(input).toHaveValue('333');dialogs(page,true);await page.getByRole('button',{name:'放弃',exact:true}).click();await expect(input).toHaveValue('120');});
for(const scope of ['group','global'])test(`${scope} saving locks input`,async({page,mock})=>{let input;if(scope==='group'){await openGroup(page);input=await draftGroup(page);}else{await login(page);await page.goto('/groups/global-config');input=field(page,'超时时长 (秒)').locator('input');await expect(input).toHaveValue('120');await input.fill('321');}mock.delay=1500;await page.getByRole('button',{name:scope==='group'?'保存策略':'保存全局策略',exact:true}).click();await expect(input).toBeDisabled();await expect(page.getByRole('button',{name:'保存中…',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'已保存',exact:true})).toBeDisabled();await expect(input).toHaveValue('321');});
for(const action of ['link','back','miniBack'])for(const accept of [false,true])test(`navigation ${action} ${accept?'accept':'cancel'} URL content draft`,async({page})=>{if(action==='miniBack')await mini(page);await groupFromList(page);const input=await draftGroup(page);const messages=dialogs(page,accept);if(action==='link')await nav(page,'总览');else if(action==='back')await page.goBack();else await page.evaluate(()=>(window as any).__miniBack());if(accept){await expect(page).toHaveURL(action==='link'?/\/dashboard$/:/\/groups$/);await expect(page.getByRole('heading',{name:action==='link'?'总览':'群管理',exact:true})).toBeVisible();expect(messages).toHaveLength(1);}else{await page.waitForTimeout(1200);await expect(page).toHaveURL(/\/groups\/-1001$/);await expect(page.getByRole('heading',{name:group.title})).toBeVisible();await expect(input).toHaveValue('321');expect(messages).toHaveLength(1);if(action!=='link'){if(action==='back')await page.goBack();else await page.evaluate(()=>(window as any).__miniBack());await page.waitForTimeout(1200);await expect(page).toHaveURL(/\/groups\/-1001$/);await expect(input).toHaveValue('321');expect(messages).toHaveLength(2);}}});
test('direct entry no in-app history back cancel preserves draft',async({page})=>{await openGroup(page);const input=await draftGroup(page);const messages=dialogs(page);await page.goBack();await page.waitForTimeout(1200);await expect(page).toHaveURL(/\/groups\/-1001$/);await expect(input).toHaveValue('321');expect(messages).toHaveLength(1);});
// Keep the historical title/test id for exact result replacement. Controller-confirmed D1:
// cancel retains the draft; accepted leave discards it; forward loads the saved baseline, clean.
test('browser forward cancel URL content draft',async({page,mock},info)=>{
 await groupFromList(page);const input=await draftGroup(page);
 const cancels=dialogs(page);await page.goBack();await page.waitForTimeout(1200);
 await expect(page).toHaveURL(/\/groups\/-1001$/);
 await expect(page.getByRole('heading',{name:group.title,exact:true})).toBeVisible();
 await expect(input).toHaveValue('321');expect(cancels).toHaveLength(1);
 const cancelledBack={url:page.url(),value:await input.inputValue(),messages:[...cancels]};
 page.removeAllListeners('dialog');const accepts=dialogs(page,true);await page.goBack();
 await expect(page).toHaveURL(/\/groups$/);
 await expect(page.getByRole('heading',{name:'群管理',exact:true})).toBeVisible();expect(accepts).toHaveLength(1);
 const acceptedLeave={url:page.url(),heading:await page.locator('h1').innerText(),messages:[...accepts]};
 page.removeAllListeners('dialog');const forwardDialogs=dialogs(page);await page.goForward();
 await expect(page).toHaveURL(/\/groups\/-1001$/);
 await expect(page.getByRole('heading',{name:group.title,exact:true})).toBeVisible();
 await page.getByRole('button',{name:'展开详细设置（4 项）'}).first().click();
 const baseline=field(page,'超时时长 (秒)');
 await expect(input).toHaveValue('120');await expect(input).toBeDisabled();
 await expect(baseline.getByRole('checkbox')).toBeChecked();
 await expect(page.getByRole('button',{name:'已保存',exact:true})).toBeDisabled();
 await expect(page.getByRole('button',{name:'保存策略',exact:true})).toHaveCount(0);
 await page.waitForTimeout(1200);expect(forwardDialogs).toHaveLength(0);expect(mock.writes).toEqual([]);
 const forward={url:page.url(),heading:await page.locator('h1').innerText(),value:await input.inputValue(),inherited:true,saved:true,messages:[...forwardDialogs]};
 // A real clean departure additionally proves no dirty guard survives the discarded draft.
 await page.goBack();await expect(page).toHaveURL(/\/groups$/);
 await expect(page.getByRole('heading',{name:'群管理',exact:true})).toBeVisible();expect(forwardDialogs).toHaveLength(0);
 await info.attach('D1-forward-saved-baseline',{body:JSON.stringify({cancelledBack,acceptedLeave,forward,cleanBack:{url:page.url(),messages:[...forwardDialogs]},writes:mock.writes}),contentType:'application/json'});
});
for(const value of ['emerald','ocean','graphite'])test(`visual routes ${value} overflow screenshots and input contrast`,async({page},info)=>{await login(page);for(const path of ['/dashboard','/groups','/groups/-1001','/groups/global-config','/llm','/prompt-editor']){await page.goto(path);await theme(page,value);await expect(page.locator('main')).toBeVisible();await page.waitForTimeout(150);expect.soft(await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth})),path).toEqual({width:info.project.name==='desktop'?1440:390,scroll:info.project.name==='desktop'?1440:390});let shot='';if(info.project.name==='desktop'&&value==='emerald'&&path==='/dashboard')shot='desktop-dashboard.png';if(info.project.name==='desktop'&&value==='ocean'&&path==='/groups/-1001')shot='group-config.png';if(info.project.name==='desktop'&&value==='graphite'&&path==='/llm'){await page.getByRole('button',{name:/^Models/}).click();shot='graphite-models.png';}if(info.project.name==='mobile'&&value==='emerald'&&path==='/groups/-1001')shot='mobile-group.png';if(shot){await expect(page).toHaveURL(new RegExp(path+'$'));await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.fixed.inset-0.z-40')).toHaveCount(0);if(path==='/groups/-1001'){await expect(page.getByRole('heading',{name:group.title})).toBeVisible();await expect(page.getByText('Fixture welcome 示例用户',{exact:true})).toBeVisible();}if(path==='/llm')await expect(page.getByText('Fixture Model',{exact:true})).toBeVisible();if(path==='/dashboard'){await expect(page.getByText('管理中的群',{exact:true}).locator('..')).toContainText('2');await expect(page.getByText('活跃验证',{exact:true}).locator('..')).toContainText('3');await expect(page.getByText('今日违规',{exact:true}).locator('..')).toContainText('4');}await page.screenshot({path:`${artifacts}/${shot}`,fullPage:true});await info.attach('screenshot-ready',{body:JSON.stringify({file:shot,url:page.url(),theme:value,heading:await page.locator('h1').innerText(),fixtureLoaded:true,unexpectedModal:false,nonProduction:true,telegram:'intercepted/simulated'}),contentType:'application/json'});}if(path==='/prompt-editor'){const input=page.locator('textarea').first();await input.fill('Readability fixture');const colors=await input.evaluate(el=>{const s=getComputedStyle(el);return {color:s.color,bg:s.backgroundColor}});await info.attach('input-colors-'+value,{body:JSON.stringify(colors),contentType:'application/json'});expect.soft(colors.color).not.toBe(colors.bg);dialogs(page,true);}}});
